<?php

echo "<h1>Hello!</h1>";

echo $this->tag->linkTo(["signup", "Sign Up Here!", 'class' => 'btn btn-primary']);


    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: 10</td>
        </tr>
        </tfoot>
        <tbody>

            <tr>
                <td>Standa</td>
                <td>Kosi</td>
                <td>Něco</td>
            </tr>
        </tbody>
    </table>
