<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <title><?php echo Phalcon\Tag::getTitle(); ?></title>
</head>
<body>
	<div class="container">
		<?php echo $this->getContent(); ?>
	</div>
	<?php  $this->assets->exists('js') ? $this->assets->outputJs() : NULL; ?>
</body>
</html>
